apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack-exporter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/esmacancs/openstack-observability.git
    targetRevision: main
    path: monitoring/openstack-exporter
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
