apiVersion: apps/v1
kind: Deployment
metadata:
  name: openstack-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openstack-exporter
  template:
    metadata:
      labels:
        app: openstack-exporter
    spec:
      containers:
      - name: openstack-exporter
        image: quay.io/niedbalski/openstack-exporter:latest
        ports:
        - containerPort: 9198
        env:
        - name: OS_AUTH_URL
          value: "http://keystone.openstack.svc.cluster.local/v3"
        - name: OS_USERNAME
          valueFrom:
            secretKeyRef:
              name: openstack-exporter-creds
              key: username
        - name: OS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: openstack-exporter-creds
              key: password
        - name: OS_PROJECT_NAME
          value: "admin"
        - name: OS_USER_DOMAIN_NAME
          value: "Default"
        - name: OS_PROJECT_DOMAIN_NAME
          value: "Default"
        - name: OS_IDENTITY_API_VERSION
          value: "3"
        - name: OS_REGION_NAME
          value: "RegionOne"

---
apiVersion: v1
kind: Service
metadata:
  name: openstack-exporter
  namespace: monitoring
spec:
  selector:
    app: openstack-exporter
  ports:
  - port: 9180
    targetPort: 9180
---
apiVersion: v1
kind: Secret
metadata:
  name: openstack-exporter-creds
  namespace: monitoring
type: Opaque
stringData:
  username: admin
  password: password
