apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-config
  namespace: openstack
data:
  ceph.conf: |
    [global]
    fsid = 9f836694-7fbe-41be-bdb3-fd49b58b5ff2
    mon_host = 10.8.132.161,10.8.132.162,10.8.132.163
    auth_cluster_required = cephx
    auth_service_required = cephx
    auth_client_required = cephx
---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-client-glance
  namespace: openstack
type: Opaque
data:
  key: # This will be populated after creating the Ceph user
