apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: general
provisioner: rancher.io/local-path   # same as your default
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false
