apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ceph-adapter-rook
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/esmacancs/openstack-gitops.git
    targetRevision: main
    path: charts/ceph-adapter-rook
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/esmacancs/openstack-gitops/main/helm-values/openstack-lab-values.yaml
      values: |
        ceph_cluster_namespace: rook-ceph
  destination:
    server: https://kubernetes.default.svc
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
