apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ceph-adapter-rook
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/esmacancs/openstack-gitops.git
    targetRevision: main
    path: charts/ceph-adapter-rook
    helm:
  valueFiles:
    - https://raw.githubusercontent.com/esmacancs/openstack-gitops/main/helm-values/openstack-lab-values.yaml
  values: |
    ceph_cluster_namespace: rook-ceph

    manifests:
      job_namespace_client_ceph_config: true
      job_namespace_client_key: true

    ceph_client:
      cinder:
        enabled: true
        caps:
          mon: "allow r"
          osd: "allow class-read object_prefix rbd_children, allow rwx pool=volumes"
      glance:
        enabled: true
        caps:
          mon: "allow r"
          osd: "allow rwx pool=images"
      nova:
        enabled: true
        caps:
          mon: "allow r"
          osd: "allow rwx pool=vms"

  destination:
    server: https://kubernetes.default.svc
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
