apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ceph-adapter-rook
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://tarballs.openstack.org/openstack-helm/
    chart: ceph-adapter-rook
    targetRevision: "*"
    helm:
      values: |
        ceph_cluster_namespace: rook-ceph
        manifests:
          namespace_client_ceph_config_generator: true
          namespace_client_key_generator: true
  destination:
    server: https://kubernetes.default.svc
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
