apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
  annotations:
    # Ensures Argo CD deploys backends first if using App-of-Apps
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://opendev.org/openstack/openstack-helm
    targetRevision: master
    path: rabbitmq
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/esmacancs/openstack-gitops/main/helm-values/openstack-lab-values.yaml
      values: |
        pod:
          replicas:
            server: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
