apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default

  source:
    repoURL: https://github.com/openstack/openstack-helm.git
    targetRevision: master
    path: mariadb
    helm:
      values: |
        pod:
          replicas:
            server: 3
        volume:
          enabled: true
          class_name: general
          size: 20Gi

  destination:
    server: https://kubernetes.default.svc
    namespace: openstack

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
