apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cinder
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6.5"
spec:
  project: default

  source:
    repoURL: https://github.com/esmacancs/openstack-gitops.git
    targetRevision: main
    path: charts/cinder
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/esmacancs/openstack-gitops/main/helm-values/openstack-lab-values.yaml
      values: |
        replicas:
          api: 3
  destination:
    server: https://kubernetes.default.svc
    namespace: openstack

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
  - group: ""
    kind: Secret
    name: cinder-volume-rbd-keyring
    jsonPointers:
    - /data
  - group: "batch"
    kind: Job
    name: cinder-storage-init
