apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://opensearch-project.github.io/helm-charts/
    targetRevision: 2.26.1
    chart: opensearch
    helm:
      values: |
        clusterName: "opensearch-cluster"
        nodeGroup: "master"
        
        # Single node for demo
        replicas: 1
        minimumMasterNodes: 1
        
        # Resource limits
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
            
        # Persistence
        persistence:
          enabled: true
          size: 8Gi
          
        # Security
        config:
          opensearch.yml: |
            cluster.name: opensearch-cluster
            network.host: 0.0.0.0
            plugins.security.disabled: true
            discovery.type: single-node
            
        # Service
        service:
          type: ClusterIP
          
  destination:
    server: https://kubernetes.default.svc
    namespace: opensearch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
