apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://opensearch-project.github.io/helm-charts/
    targetRevision: 2.26.1
    chart: opensearch
    helm:
      values: |
        clusterName: "opensearch"
        nodeGroup: "master"
        
        # Single node setup
        replicas: 1
        minimumMasterNodes: 1
        
        # Reduced resources for faster startup
        resources:
          requests:
            cpu: "100m"
            memory: "1Gi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
            
        # Disable security for simplicity
        config:
          opensearch.yml: |
            cluster.name: opensearch
            network.host: 0.0.0.0
            plugins.security.disabled: true
            discovery.type: single-node
            bootstrap.memory_lock: false
            
        # Persistence
        persistence:
          enabled: false
          
  destination:
    server: https://kubernetes.default.svc
    namespace: opensearch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
