apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://opensearch-project.github.io/helm-charts/
    targetRevision: 2.26.1
    chart: opensearch
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/esmacancs/openstack-gitops/main/helm-values/openstack-lab-values.yaml
        - https://raw.githubusercontent.com/esmacancs/openstack-gitops/main/helm-values/openstack-lab-values.yaml
