apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: elasticsearch
    targetRevision: "8.5.1"
    helm:
      values: |
        replicas: 3
        minimumMasterNodes: 2
        
        esConfig:
          elasticsearch.yml: |
            cluster.name: "openstack-logs"
            network.host: 0.0.0.0
            
        resources:
          requests:
            cpu: "1000m"
            memory: "2Gi"
          limits:
            cpu: "2000m"
            memory: "4Gi"
            
        volumeClaimTemplate:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: general
          resources:
            requests:
              storage: 100Gi

  destination:
    server: https://kubernetes.default.svc
    namespace: logging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
