apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/esmacancs/openstack-gitops.git
    targetRevision: main
    path: argocd/children
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
